# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read a given file in sparse (LIBSVM) format to dense R matrix and R vector.
#'
#' @param              filename                the filename of the data in sparse file format. The Tilde Character isn't supported for f filename!  
#' @param              verbose         show verbose output?
#' @param              zeroBased       do the indices in the file start with 0, e.g. -1 0:2 1:4 ...?
#' @keywords   IO 
#' @note               this routine is nearly a 1:1 adoptation from the LIBSVM original code.
#' @return             the data is read into an R matrix and an R vector, containing the data
#'                                     and the labels. note, that these are not in sparse format, but are dense.
#'
#' @export
cppdummy <- function(i) {
    invisible(.Call('crushSVM_cppdummy', PACKAGE = 'crushSVM', i))
}

