# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loss <- function(kernel, loss, C, offset, unconstrained = FALSE, cacheSize = 0x4000000) 		: m_kernel(kernel) 		, m_loss(loss) 		, m_C(C) 		, m_offset(offset) 		, m_unconstrained(unconstrained) 		, m_epochs(0) 		, m_cacheSize(cacheSizeL) {
    .Call('swarmsvm_loss', PACKAGE = 'swarmsvm', kernel, loss, C, offset, unconstrained, cacheSize)
}

rcpparma_outerproduct <- function(x) {
    .Call('swarmsvm_rcpparma_outerproduct', PACKAGE = 'swarmsvm', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('swarmsvm_rcpparma_innerproduct', PACKAGE = 'swarmsvm', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('swarmsvm_rcpparma_bothproducts', PACKAGE = 'swarmsvm', x)
}

